[workspace]
members = ["cargo:."]

# See https://opensource.axo.dev/cargo-dist/
[dist]
cargo-dist-version = "0.28.0"
ci = "github"
installers = ["shell"]
targets = [
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
]
install-updater = false
