//! rmcp-based MCP server exposing the seven fixed `cc-uplink` channel tools
//! (list, describe, observe, act, send, recv, doctor).
//!
//! Adapted against rmcp 2.2.0's actual macro/type surface (see
//! `~/.cargo/registry/src/*/rmcp-2.2.0/tests/test_tool_macros.rs` for the
//! reference patterns this file follows). Notable differences from an older
//! rmcp API sketch:
//! - `Parameters` lives at `rmcp::handler::server::wrapper::Parameters`, not
//!   under a `tool` submodule.
//! - The unified content union type is `ContentBlock` (`model::ContentBlock`),
//!   not `Content` — 2.x renamed it and only a stale `rust,ignore` doc
//!   example in the crate still says `Content`.
//! - `CallToolResult::success`/`error` take `Vec<ContentBlock>`.
//! - `#[tool_router]` names a `tool_router: ToolRouter<Self>` field and
//!   exposes `Self::tool_router()` (generated by the macro) to build it in
//!   `new()`. `#[tool_handler]` defaults to routing calls through a *fresh*
//!   `Self::tool_router()` per call, which leaves the stored field unused;
//!   `#[tool_handler(router = self.tool_router)]` makes it reuse the stored
//!   instance field instead (matches the `Server` pattern in
//!   `tests/test_tool_macros.rs`, avoids rebuilding the routing table on
//!   every call and the resulting `dead_code` warning).

use std::sync::Arc;

use rmcp::{
    ServerHandler, ServiceExt,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{CallToolResult, ContentBlock, ServerCapabilities, ServerInfo},
    tool, tool_handler, tool_router,
    transport::stdio,
};
use schemars::JsonSchema;
use serde::Deserialize;

use crate::core::driver::SendRequest;
use crate::core::registry::Registry;
use crate::error::DriverError;

/// Map a driver `Result` into MCP-tool-ready text: `Ok` becomes pretty JSON,
/// `Err` becomes the rendered driver-error text (`DriverError::render`).
pub fn render_result<T: serde::Serialize>(
    r: Result<T, DriverError>,
    driver: &str,
) -> Result<String, String> {
    match r {
        Ok(v) => Ok(serde_json::to_string_pretty(&v).unwrap_or_else(|e| e.to_string())),
        Err(e) => Err(e.render(driver)),
    }
}

/// Channel prefix (before the first `:`), falling back to `"core"` when the
/// address has no colon at all or an empty prefix (e.g. a bare channel name
/// that failed to parse, or a leading `:`).
fn driver_of(addr: &str) -> &str {
    addr.split_once(':')
        .map(|(p, _)| p)
        .filter(|s| !s.is_empty())
        .unwrap_or("core")
}

fn text_ok(s: String) -> CallToolResult {
    CallToolResult::success(vec![ContentBlock::text(s)])
}

fn text_err(s: String) -> CallToolResult {
    CallToolResult::error(vec![ContentBlock::text(s)])
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct DescribeParams {
    pub channel: String,
    pub op: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SendParams {
    pub channel: String,
    pub message: String,
    /// full | short | none — how much reply instruction to embed
    pub reply_hint: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct InvokeParams {
    pub channel: String,
    pub op: String,
    /// Op arguments object (see channel_describe for the op's schema).
    /// Typed as a JSON object rather than `serde_json::Value`: schemars
    /// renders `Value` as the boolean schema `true`, which Claude Code's
    /// MCP client rejects ("Invalid input at inputSchema.properties.args"),
    /// killing the whole tool list.
    pub args: Option<serde_json::Map<String, serde_json::Value>>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct RecvParams {
    pub cursor: Option<u64>,
}

#[derive(Clone)]
pub struct Uplink {
    reg: Arc<Registry>,
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl Uplink {
    pub fn new(reg: Arc<Registry>) -> Self {
        Self {
            reg,
            tool_router: Self::tool_router(),
        }
    }

    #[tool(description = "List all channels across drivers with capability summaries")]
    async fn channel_list(&self) -> CallToolResult {
        let all = self.reg.list_all().await;
        let mut lines = vec![];
        for (info, chans) in all {
            lines.push(format!("# driver {} — {}", info.id, info.summary));
            for c in chans {
                lines.push(format!(
                    "{} | labels:{:?} | {}",
                    c.channel, c.labels, c.detail
                ));
            }
        }
        text_ok(if lines.is_empty() {
            "no channels".into()
        } else {
            lines.join("\n")
        })
    }

    #[tool(
        description = "Get the JSON Schema for a channel op (call before first invoke of an op)"
    )]
    async fn channel_describe(&self, Parameters(p): Parameters<DescribeParams>) -> CallToolResult {
        match self.reg.driver_for(&p.channel) {
            Ok((d, _)) => {
                let ops = d.ops();
                let sel: Vec<_> = ops
                    .into_iter()
                    .filter(|o| p.op.as_deref().map(|x| x == o.op).unwrap_or(true))
                    .collect();
                text_ok(serde_json::to_string_pretty(&sel).unwrap_or_default())
            }
            Err(e) => text_err(e.render(driver_of(&p.channel))),
        }
    }

    #[tool(
        description = "Send an async message to a channel (tmux: full inject+verify+Enter cycle)"
    )]
    async fn channel_send(&self, Parameters(p): Parameters<SendParams>) -> CallToolResult {
        let hint = match p.reply_hint.as_deref() {
            Some("short") => crate::core::driver::ReplyHint::Short,
            Some("none") => crate::core::driver::ReplyHint::None,
            _ => crate::core::driver::ReplyHint::Full,
        };
        match self.reg.driver_for(&p.channel) {
            Ok((d, addr)) => match render_result(
                d.send(
                    &addr,
                    SendRequest {
                        message: p.message,
                        reply_hint: hint,
                    },
                )
                .await,
                driver_of(&p.channel),
            ) {
                Ok(s) => text_ok(s),
                Err(s) => text_err(s),
            },
            Err(e) => text_err(e.render(driver_of(&p.channel))),
        }
    }

    #[tool(
        description = "Invoke a read-only op on a channel (read, await_idle — see channel_describe)"
    )]
    async fn channel_observe(&self, Parameters(p): Parameters<InvokeParams>) -> CallToolResult {
        self.invoke_class(p, false).await
    }

    #[tool(
        description = "Invoke a mutating op on a channel (type, keys, ask, label, generate, edit — see channel_describe)"
    )]
    async fn channel_act(&self, Parameters(p): Parameters<InvokeParams>) -> CallToolResult {
        self.invoke_class(p, true).await
    }

    async fn invoke_class(&self, p: InvokeParams, mutating: bool) -> CallToolResult {
        match self.reg.driver_for(&p.channel) {
            Ok((d, addr)) => {
                match d.ops().into_iter().find(|o| o.op == p.op) {
                    Some(spec) if spec.mutating != mutating => {
                        let (is, right) = if spec.mutating {
                            ("mutating", "channel_act")
                        } else {
                            ("read-only", "channel_observe")
                        };
                        return text_err(
                            DriverError::new(
                                crate::error::ErrorKind::Invalid,
                                format!("op '{}' is {is} — call it via {right}", p.op),
                            )
                            .render(driver_of(&p.channel)),
                        );
                    }
                    None => {
                        return text_err(
                            DriverError::new(
                                crate::error::ErrorKind::NotFound,
                                format!("no op '{}'", p.op),
                            )
                            .with_hint("run channel_describe")
                            .render(driver_of(&p.channel)),
                        );
                    }
                    Some(_) => {}
                }
                match render_result(
                    d.invoke(
                        &addr,
                        &p.op,
                        p.args
                            .map(serde_json::Value::Object)
                            .unwrap_or_else(|| serde_json::json!({})),
                    )
                    .await,
                    driver_of(&p.channel),
                ) {
                    Ok(s) => text_ok(s),
                    Err(s) => text_err(s),
                }
            }
            Err(e) => text_err(e.render(driver_of(&p.channel))),
        }
    }

    #[tool(description = "Drain inbound message envelopes received since cursor (non-blocking)")]
    async fn channel_recv(&self, Parameters(p): Parameters<RecvParams>) -> CallToolResult {
        let mut items = vec![];
        let mut next = p.cursor.unwrap_or(0);
        for d in self.reg.drivers() {
            if let Ok(batch) = d.recv(p.cursor).await {
                next = next.max(batch.next_cursor);
                items.extend(batch.items);
            }
        }
        text_ok(
            serde_json::to_string_pretty(&serde_json::json!({
                "items": items, "next_cursor": next
            }))
            .unwrap_or_default(),
        )
    }

    #[tool(description = "Aggregated diagnostics across all drivers")]
    async fn channel_doctor(&self) -> CallToolResult {
        let reports = self.reg.doctor_all().await;
        let mut out = vec!["cc-uplink doctor".to_string(), "---".to_string()];
        for r in &reports {
            out.push(format!(
                "[{}] {}",
                r.driver,
                if r.ok { "OK" } else { "DEGRADED" }
            ));
            out.extend(r.lines.iter().map(|l| format!("  {l}")));
        }
        text_ok(out.join("\n"))
    }
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for Uplink {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build()).with_instructions(
            "cc-uplink: unified outbound channels. Start with channel_list; \
             call channel_describe before the first use of an op; read-only ops \
             go through channel_observe, mutating ops through channel_act; never \
             poll for replies — they arrive in your own pane (channel_recv is an \
             audit log).",
        )
    }
}

/// Build the driver registry from config, registering the tmux driver and
/// the image driver per config. `TmuxDriver` construction failures are
/// logged to stderr and skipped rather than crashing the server — the
/// missing driver simply won't appear in `channel_list`/`channel_doctor`.
/// The image driver is registered only when at least one image backend is
/// enabled.
pub async fn build_registry() -> Arc<Registry> {
    let cfg = crate::config::Config::load();
    let mut reg = Registry::new();
    if cfg.drivers.tmux.enabled {
        match crate::drivers::tmux::TmuxDriver::new(cfg.drivers.tmux).await {
            Ok(d) => reg.register(d),
            Err(e) => eprintln!("cc-uplink: tmux driver unavailable: {}", e.message),
        }
    }
    let mut backends: Vec<Box<dyn crate::drivers::image::ImageBackend>> = Vec::new();
    if cfg.drivers.image_openai.enabled {
        backends.push(Box::new(crate::drivers::image::openai::OpenAiBackend::new(
            cfg.drivers.image_openai,
        )));
    }
    if cfg.drivers.image_codex.enabled {
        backends.push(Box::new(crate::drivers::image::codex::CodexBackend::new(
            cfg.drivers.image_codex,
        )));
    }
    if !backends.is_empty() {
        reg.register(Arc::new(crate::drivers::image::ImageDriver::from_backends(
            backends,
        )));
    }
    Arc::new(reg)
}

/// Build the registry and serve the seven-tool MCP server over stdio until the
/// client disconnects (stdin EOF).
pub async fn serve() -> anyhow::Result<()> {
    let reg = build_registry().await;
    let service = Uplink::new(reg).serve(stdio()).await?;
    service.waiting().await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    #[test]
    fn maps_driver_error_to_rendered_text() {
        let e = crate::error::DriverError::new(crate::error::ErrorKind::NotFound, "x");
        let s = super::render_result::<serde_json::Value>(Err(e), "tmux").unwrap_err();
        assert!(s.contains("uplink error [tmux:NotFound]: x"));
    }

    #[test]
    fn maps_ok_to_pretty_json() {
        let v = serde_json::json!({"a": 1});
        let s = super::render_result(Ok(v), "tmux").unwrap();
        assert!(s.contains("\"a\": 1"));
    }

    #[test]
    fn driver_of_falls_back_to_core_without_prefix() {
        assert_eq!(super::driver_of("tmux:main"), "tmux");
        assert_eq!(super::driver_of("nocolon"), "core");
        assert_eq!(super::driver_of(":bare"), "core");
    }

    use std::sync::Arc;

    use crate::config::ImageOpenAiCfg;
    use crate::core::registry::Registry;
    use crate::drivers::image::{ImageBackend, ImageDriver, openai::OpenAiBackend};
    use crate::error::ErrorKind;

    #[tokio::test]
    async fn image_driver_routes_via_registry() {
        let mut reg = Registry::new();
        let cfg = ImageOpenAiCfg {
            enabled: true,
            api_key_env: "CC_UPLINK_T_MCP_NOKEY".into(),
            model: "gpt-image-1".into(),
            base_url: "http://127.0.0.1:9".into(),
        };
        let backends: Vec<Box<dyn ImageBackend>> = vec![Box::new(OpenAiBackend::new(cfg))];
        reg.register(Arc::new(ImageDriver::from_backends(backends)));
        let (d, addr) = reg.driver_for("image:openai").unwrap();
        assert_eq!(addr, "openai");
        // no key set → invoke fails Unavailable through the full routing path
        let e = d
            .invoke(&addr, "generate", serde_json::json!({"prompt": "x"}))
            .await
            .err()
            .unwrap();
        assert!(matches!(e.kind, ErrorKind::Unavailable));
        let list = reg.list_all().await;
        assert!(
            list.iter()
                .any(|(i, cs)| i.id == "image" && cs.iter().any(|c| c.channel == "image:openai"))
        );
    }

    #[tokio::test]
    async fn observe_rejects_mutating_op_and_names_the_right_tool() {
        let mut reg = Registry::new();
        let cfg = ImageOpenAiCfg {
            enabled: true,
            api_key_env: "CC_UPLINK_T_SPLIT_NOKEY".into(),
            model: "gpt-image-1".into(),
            base_url: "http://127.0.0.1:9".into(),
        };
        let backends: Vec<Box<dyn ImageBackend>> = vec![Box::new(OpenAiBackend::new(cfg))];
        reg.register(Arc::new(ImageDriver::from_backends(backends)));
        let u = super::Uplink::new(Arc::new(reg));
        let out = u
            .invoke_class(
                super::InvokeParams {
                    channel: "image:openai".into(),
                    op: "generate".into(),
                    args: None,
                },
                false, // called via channel_observe
            )
            .await;
        let txt = format!("{out:?}");
        assert!(txt.contains("channel_act"), "must redirect to the act tool: {txt}");
    }
}
