//! rmcp-based MCP server exposing the six fixed `cc-uplink` channel tools.
//!
//! Adapted against rmcp 2.2.0's actual macro/type surface (see
//! `~/.cargo/registry/src/*/rmcp-2.2.0/tests/test_tool_macros.rs` for the
//! reference patterns this file follows). Notable differences from an older
//! rmcp API sketch:
//! - `Parameters` lives at `rmcp::handler::server::wrapper::Parameters`, not
//!   under a `tool` submodule.
//! - The unified content union type is `ContentBlock` (`model::ContentBlock`),
//!   not `Content` — 2.x renamed it and only a stale `rust,ignore` doc
//!   example in the crate still says `Content`.
//! - `CallToolResult::success`/`error` take `Vec<ContentBlock>`.
//! - `#[tool_router]` names a `tool_router: ToolRouter<Self>` field and
//!   exposes `Self::tool_router()` (generated by the macro) to build it in
//!   `new()`. `#[tool_handler]` defaults to routing calls through a *fresh*
//!   `Self::tool_router()` per call, which leaves the stored field unused;
//!   `#[tool_handler(router = self.tool_router)]` makes it reuse the stored
//!   instance field instead (matches the `Server` pattern in
//!   `tests/test_tool_macros.rs`, avoids rebuilding the routing table on
//!   every call and the resulting `dead_code` warning).

use std::sync::Arc;

use rmcp::{
    ServerHandler, ServiceExt,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{CallToolResult, ContentBlock, ServerCapabilities, ServerInfo},
    tool, tool_handler, tool_router,
    transport::stdio,
};
use schemars::JsonSchema;
use serde::Deserialize;

use crate::core::driver::SendRequest;
use crate::core::registry::Registry;
use crate::error::DriverError;

/// Map a driver `Result` into MCP-tool-ready text: `Ok` becomes pretty JSON,
/// `Err` becomes the rendered driver-error text (`DriverError::render`).
pub fn render_result<T: serde::Serialize>(
    r: Result<T, DriverError>,
    driver: &str,
) -> Result<String, String> {
    match r {
        Ok(v) => Ok(serde_json::to_string_pretty(&v).unwrap_or_else(|e| e.to_string())),
        Err(e) => Err(e.render(driver)),
    }
}

/// Channel prefix (before `:`), falling back to `"core"` for addresses that
/// don't carry one (e.g. a bare channel name that failed to parse).
fn driver_of(addr: &str) -> &str {
    addr.split(':')
        .next()
        .filter(|s| !s.is_empty())
        .unwrap_or("core")
}

fn text_ok(s: String) -> CallToolResult {
    CallToolResult::success(vec![ContentBlock::text(s)])
}

fn text_err(s: String) -> CallToolResult {
    CallToolResult::error(vec![ContentBlock::text(s)])
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct DescribeParams {
    pub channel: String,
    pub op: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SendParams {
    pub channel: String,
    pub message: String,
    /// full | short | none — how much reply instruction to embed
    pub reply_hint: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct InvokeParams {
    pub channel: String,
    pub op: String,
    pub args: Option<serde_json::Value>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct RecvParams {
    pub cursor: Option<u64>,
}

#[derive(Clone)]
pub struct Uplink {
    reg: Arc<Registry>,
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl Uplink {
    pub fn new(reg: Arc<Registry>) -> Self {
        Self {
            reg,
            tool_router: Self::tool_router(),
        }
    }

    #[tool(description = "List all channels across drivers with capability summaries")]
    async fn channel_list(&self) -> CallToolResult {
        let all = self.reg.list_all().await;
        let mut lines = vec![];
        for (info, chans) in all {
            lines.push(format!("# driver {} — {}", info.id, info.summary));
            for c in chans {
                lines.push(format!(
                    "{} | labels:{:?} | {}",
                    c.channel, c.labels, c.detail
                ));
            }
        }
        text_ok(if lines.is_empty() {
            "no channels".into()
        } else {
            lines.join("\n")
        })
    }

    #[tool(
        description = "Get the JSON Schema for a channel op (call before first invoke of an op)"
    )]
    async fn channel_describe(&self, Parameters(p): Parameters<DescribeParams>) -> CallToolResult {
        match self.reg.driver_for(&p.channel) {
            Ok((d, _)) => {
                let ops = d.ops();
                let sel: Vec<_> = ops
                    .into_iter()
                    .filter(|o| p.op.as_deref().map(|x| x == o.op).unwrap_or(true))
                    .collect();
                text_ok(serde_json::to_string_pretty(&sel).unwrap_or_default())
            }
            Err(e) => text_err(e.render(driver_of(&p.channel))),
        }
    }

    #[tool(
        description = "Send an async message to a channel (tmux: full inject+verify+Enter cycle)"
    )]
    async fn channel_send(&self, Parameters(p): Parameters<SendParams>) -> CallToolResult {
        let hint = match p.reply_hint.as_deref() {
            Some("short") => crate::core::driver::ReplyHint::Short,
            Some("none") => crate::core::driver::ReplyHint::None,
            _ => crate::core::driver::ReplyHint::Full,
        };
        match self.reg.driver_for(&p.channel) {
            Ok((d, addr)) => match render_result(
                d.send(
                    &addr,
                    SendRequest {
                        message: p.message,
                        reply_hint: hint,
                    },
                )
                .await,
                driver_of(&p.channel),
            ) {
                Ok(s) => text_ok(s),
                Err(s) => text_err(s),
            },
            Err(e) => text_err(e.render(driver_of(&p.channel))),
        }
    }

    #[tool(description = "Invoke a capability op on a channel (see channel_describe for schemas)")]
    async fn channel_invoke(&self, Parameters(p): Parameters<InvokeParams>) -> CallToolResult {
        match self.reg.driver_for(&p.channel) {
            Ok((d, addr)) => match render_result(
                d.invoke(&addr, &p.op, p.args.unwrap_or(serde_json::json!({})))
                    .await,
                driver_of(&p.channel),
            ) {
                Ok(s) => text_ok(s),
                Err(s) => text_err(s),
            },
            Err(e) => text_err(e.render(driver_of(&p.channel))),
        }
    }

    #[tool(description = "Drain inbound message envelopes received since cursor (non-blocking)")]
    async fn channel_recv(&self, Parameters(p): Parameters<RecvParams>) -> CallToolResult {
        let mut items = vec![];
        let mut next = p.cursor.unwrap_or(0);
        for d in self.reg.drivers() {
            if let Ok(batch) = d.recv(p.cursor).await {
                next = next.max(batch.next_cursor);
                items.extend(batch.items);
            }
        }
        text_ok(
            serde_json::to_string_pretty(&serde_json::json!({
                "items": items, "next_cursor": next
            }))
            .unwrap_or_default(),
        )
    }

    #[tool(description = "Aggregated diagnostics across all drivers")]
    async fn channel_doctor(&self) -> CallToolResult {
        let reports = self.reg.doctor_all().await;
        let mut out = vec!["cc-uplink doctor".to_string(), "---".to_string()];
        for r in &reports {
            out.push(format!(
                "[{}] {}",
                r.driver,
                if r.ok { "OK" } else { "DEGRADED" }
            ));
            out.extend(r.lines.iter().map(|l| format!("  {l}")));
        }
        text_ok(out.join("\n"))
    }
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for Uplink {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build()).with_instructions(
            "cc-uplink: unified outbound channels. Start with channel_list; \
             call channel_describe before the first invoke of an op; never poll for replies — \
             they arrive in your own pane (channel_recv is an audit log).",
        )
    }
}

/// Build the driver registry from config, registering `TmuxDriver` when
/// enabled and constructible. A construction failure is logged to stderr and
/// skipped rather than crashing the server — the missing driver simply won't
/// appear in `channel_list`/`channel_doctor`.
pub async fn build_registry() -> Arc<Registry> {
    let cfg = crate::config::Config::load();
    let mut reg = Registry::new();
    if cfg.drivers.tmux.enabled {
        match crate::drivers::tmux::TmuxDriver::new(cfg.drivers.tmux).await {
            Ok(d) => reg.register(d),
            Err(e) => eprintln!("cc-uplink: tmux driver unavailable: {}", e.message),
        }
    }
    Arc::new(reg)
}

/// Build the registry and serve the six-tool MCP server over stdio until the
/// client disconnects (stdin EOF).
pub async fn serve() -> anyhow::Result<()> {
    let reg = build_registry().await;
    let service = Uplink::new(reg).serve(stdio()).await?;
    service.waiting().await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    #[test]
    fn maps_driver_error_to_rendered_text() {
        let e = crate::error::DriverError::new(crate::error::ErrorKind::NotFound, "x");
        let s = super::render_result::<serde_json::Value>(Err(e), "tmux").unwrap_err();
        assert!(s.contains("uplink error [tmux:NotFound]: x"));
    }

    #[test]
    fn maps_ok_to_pretty_json() {
        let v = serde_json::json!({"a": 1});
        let s = super::render_result(Ok(v), "tmux").unwrap();
        assert!(s.contains("\"a\": 1"));
    }
}
